services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: kyc-mongodb
    restart: unless-stopped
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_DATABASE: kyc_db
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - kyc-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/kyc_db --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # KYC Service
  kyc-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kyc-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017/kyc_db
      LOG_LEVEL: debug
      # Sumsub credentials (set these in .env file)
      SUMSUB_APP_TOKEN: ${SUMSUB_APP_TOKEN}
      SUMSUB_SECRET_KEY: ${SUMSUB_SECRET_KEY}
      SUMSUB_BASE_URL: ${SUMSUB_BASE_URL:-https://api.sumsub.com}
      SUMSUB_WEBHOOK_SECRET: ${SUMSUB_WEBHOOK_SECRET}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - kyc-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Mongo Express - MongoDB Admin UI (optional, for development)
  mongo-express:
    image: mongo-express:latest
    container_name: kyc-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - kyc-network
    profiles:
      - dev # Only start with --profile dev

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  kyc-network:
    driver: bridge
