services:
  # MongoDB for local development
  mongodb:
    image: mongo:7
    container_name: kyc-mongodb-dev
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: kyc_db
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - kyc-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/kyc_db --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Mongo Express - MongoDB Admin UI
  mongo-express:
    image: mongo-express:latest
    container_name: kyc-mongo-express-dev
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - kyc-network

volumes:
  mongodb_dev_data:
    driver: local

networks:
  kyc-network:
    driver: bridge
