export enum DocumentType {
  PASSPORT = 'PASSPORT',
  ID_CARD = 'ID_CARD',
  DRIVERS_LICENSE = 'DRIVERS_LICENSE',
  RESIDENCE_PERMIT = 'RESIDENCE_PERMIT',
  PROOF_OF_RESIDENCE = 'PROOF_OF_RESIDENCE',
  SELFIE = 'SELFIE',
}
